services:
  api:
    build:
      context: ./backend
    container_name: youlend-api
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    develop:
      watch:
        - action: rebuild
          path: ./api
          target: index.js
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json