replicas: 1
minimumMasterNodes: 1

# Resource limits
resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

# Storage configuration
volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: "standard"

# Security settings
esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: true
    xpack.monitoring.enabled: true
    xpack.watcher.enabled: true
    xpack.ml.enabled: true

extraEnvs:
  - name: ELASTIC_USERNAME
    value: "elastic"
  - name: ELASTIC_PASSWORD
    value: "password"


# Anti-affinity to spread across nodes
antiAffinity: "soft"

# Node tolerations
tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "monitoring"
    effect: "NoSchedule"

# Node affinity
nodeAffinity:
  preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      preference:
        matchExpressions:
          - key: node-role.kubernetes.io/monitoring
            operator: Exists

# Security settings
securityContext:
  fsGroup: 1000
  runAsUser: 1000

# Network settings
service:
  type: ClusterIP
  
# JVM heap size
esJavaOpts: "-Xmx1g -Xms1g"
