replicas: 1

# Resource limits
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "1Gi"

# Security settings
securityContext:
  fsGroup: 1000
  runAsUser: 1000

# Service configuration
service:
  type: ClusterIP
  ports:
    - name: beats
      port: 5044
      protocol: TCP
      targetPort: 5044
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080

readinessProbe:
  httpGet:
    path: /
    port: 9600
  initialDelaySeconds: 60
  # periodSeconds: 30
  timeoutSeconds: 30
  # failureThreshold: 6
  # successThreshold: 1
livenessProbe:
  httpGet:
    path: /
    port: 9600
  initialDelaySeconds: 60
  # periodSeconds: 30
  timeoutSeconds: 30
  # failureThreshold: 6
  # successThreshold: 1

# Node tolerations
tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "monitoring"
    effect: "NoSchedule"

# Logstash configuration
logstashConfig:
  logstash.yml: |
    http.host: "0.0.0.0"
    monitoring.elasticsearch.hosts: ["http://elasticsearch-master:9200"]

extraEnvs:
  - name: ELASTICSEARCH_USERNAME
    value: "elastic"
  - name: ELASTICSEARCH_PASSWORD
    value: "password"

# Logstash pipeline configuration
logstashPipeline:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-master:9200"]
        user => "${ELASTICSEARCH_USERNAME}"
        password => "${ELASTICSEARCH_PASSWORD}"
        index => "logstash-%{+YYYY.MM.dd}"
      }
    }

