elasticsearchHosts: "http://elasticsearch-master:9200"
# Resource limits
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "1Gi" 

extraEnvs:
  - name: ELASTICSEARCH_USERNAME
    value: "elastic"
  - name: ELASTICSEARCH_PASSWORD
    value: "password"
  - name: "SERVER_BASEPATH"
    value: "/kibana"
  - name: "SERVER_REWRITEBASEPATH"
    value: "false"

# Kibana configuration
kibanaConfig:
  kibana.yml: |
    server.name: kibana
    server.host: "0.0.0.0"
    elasticsearch.hosts: ["http://elasticsearch-master:9200"]
    elasticsearch.username: "${ELASTICSEARCH_USERNAME}"
    elasticsearch.password: "${ELASTICSEARCH_PASSWORD}"
    monitoring.ui.container.elasticsearch.enabled: true
    server.basePath: "/kibana"
    server.rewriteBasePath: false
