replicas: 1
# Resource limits
resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

# Logstash configuration
logstashConfig:
  logstash.yml: |
    http.host: "0.0.0.0"
    monitoring.elasticsearch.hosts: ["http://elasticsearch-master:9200"]

extraEnvs:
  - name: ELASTICSEARCH_USERNAME
    value: "elastic"
  - name: ELASTICSEARCH_PASSWORD
    value: "password"

# Logstash pipeline configuration
logstashPipeline:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-master:9200"]
        user => "${ELASTICSEARCH_USERNAME}"
        password => "${ELASTICSEARCH_PASSWORD}"
        index => "logstash-%{+YYYY.MM.dd}"
      }
    }

